### ISSUE TITLE
Index out of bounds with line_widths

### ISSUE THREAD

**Issue by niklas88** [invor/simplestGraphRendering#8]
At [line 984](https://github.com/invor/simplestGraphRendering/blob/master/src/simplestGraphRendering.cpp#L984) we index line_widths with i that goes from 0 to index_offsets.size()-1 (exclusive). However in loadGraphData in addition to adding to index_offsets whenever we add to line_widths (at line 927) we also add to it in line 845 and 937. So index_offsets is 2 elements larger than line_widths not 1.

I fixed this by removing line 845 but this assumes that there are no edges with width==0 at the beginning so I'm not sure this is right, therefor this issue.

**Comment by invor** [comment]
I accidently added line 845 just recently and I think it's correct to remove it again. If line 845 is removed, edged with width==0 at the beginning will simply be ignored as the first index offset corresponds to the first edge with width != 0. I think it's alright to handle it this way for now, as these edges couldn't be displayed anyway and keeping line 845 causes a misalignment between index_offsets and line_widths. Good you caught this bug :)
Closed via bdd2eb1de8e9a9e6384616d762dc55ca598ad384
